lullabot_recipe_list:
  pattern:  /recipes
  defaults: { _controller: LullabotRecipeBundle:Default:index }

lullabot_recipe_show:
  pattern:  /recipes/{id}
  defaults: { _controller: LullabotRecipeBundle:Default:show }
  requirements:
    id: \d+

lullabot_recipe_create:
  pattern:  /recipes/create
  defaults: { _controller: LullabotRecipeBundle:Default:create }
