parameters:
    lullabot_drupal_user_provider.class: Lullabot\DrupalUserBundle\Security\User\WebserviceUserProvider

services:
    lullabot_drupal_user_provider:
        class: %lullabot_drupal_user_provider.class%
