login:
    pattern:   /login
    defaults:  { _controller: LullabotDrupalUserBundle:Default:login }

login_check:
    pattern:   /login_check

lullabot_drupal_user:
    resource: "@LullabotDrupalUserBundle/Resources/config/routing.yml"
    prefix:   /

lullabot_recipe:
    resource: "@LullabotRecipeBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    path:  /
    defaults: { _controller: LullabotRecipeBundle:Default:index }
