jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    providers:
        webservice:
            id: lullabot_drupal_user_provider

    encoders:
        Lullabot\DrupalUserBundle\Security\User\WebserviceUser: plaintext

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
